### ISSUE TITLE
安装nodejs后仍无法执行

### ISSUE THREAD

**Issue by leoyeer** [forclan/alfred-chrome-bookmark#4]
如题

**Comment by forclan** [comment]
能更加详细的说明下吗, 刚重新下载后发现可以运行。
在shell执行`node -v`能获取到数据吗

**Comment by leoyeer** [comment]
node -v 吐的版本号：v10.7.0。nodejs应该是安装好的。是不是还有其它的依赖不 ？具体的表现就是 在Alfred输入了关键词+搜索词，没有搜索结果，中英文都没有

**Comment by forclan** [comment]
这个库的依赖都打到包里面了, 所以应该不会出现依赖的问题。
你的alfred版本是多少, 或者你到alfred里面找到这个包点下debug发一下debug信息?

**Comment by leoyeer** [comment]
关键词我改成 c 了，/Users/xxx是用户目录，输入字符： c git 
错误日志如下

[2018-09-14 15:24:13][ERROR: input.scriptfilter] Code 1: /Users/xxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.06A3D3FF-F1D4-4753-9C28-39306169AFA1/bookmark.js:138
    let pinyin = replaceHanZiWithPingYin(val.name);
                                             ^

TypeError: Cannot read property 'name' of null
    at allBookmark.map.val (/Users/xxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.06A3D3FF-F1D4-4753-9C28-39306169AFA1/bookmark.js:138:46)
    at Array.map (<anonymous>)
    at getBookmarkInPinYin (/Users/xxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.06A3D3FF-F1D4-4753-9C28-39306169AFA1/bookmark.js:137:32)
    at Object.<anonymous> (/Users/xxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.06A3D3FF-F1D4-4753-9C28-39306169AFA1/index.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
[2018-09-14 15:24:13][ERROR: input.scriptfilter] Code 1: /Users/xxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.06A3D3FF-F1D4-4753-9C28-39306169AFA1/bookmark.js:138
    let pinyin = replaceHanZiWithPingYin(val.name);
                                             ^

TypeError: Cannot read property 'name' of null
    at allBookmark.map.val (/Users/xxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.06A3D3FF-F1D4-4753-9C28-39306169AFA1/bookmark.js:138:46)
    at Array.map (<anonymous>)
    at getBookmarkInPinYin (/Users/xxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.06A3D3FF-F1D4-4753-9C28-39306169AFA1/bookmark.js:137:32)
    at Object.<anonymous> (/Users/xxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.06A3D3FF-F1D4-4753-9C28-39306169AFA1/index.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)Ï

**Comment by forclan** [comment]
代码的更新似乎有点问题, 稍晚一点我会打出一个包。

**Comment by forclan** [comment]
麻烦下载这个文件试一下: https://github.com/forclan/alfred-chrome-bookmark/blob/change/Chrome%20Bookmark%20for%20default%20user.alfredworkflow

如果还是有问题麻烦贴一下错误的日志, 里面可能涉及到一些私密信息, 注意处理一下。

**Comment by leoyeer** [comment]
[2018-09-15 22:06:39][ERROR: input.scriptfilter] Code 1: Sat, 15 Sep 2018 14:06:39 GMT getBookmarkInPinYin /Users/leoyeer/Library/Application Support/Google/Chrome/Default/Bookmarks
TypeError: Cannot read property 'name' of null
    at allBookmark.map.str 

(/Users/xxx/Documents/backup/Alfred.alfredpreferences/workflows/user.workflow.06A3D3FF-F1D4-4753-9C28-39306169AFA1/bookmark.js:149:50)
    at Array.map (<anonymous>)
    at getBookmarkInPinYin 

(/Users/xxx/Documents/backup/Alfred.alfredpreferences/workflows/user.workflow.06A3D3FF-F1D4-4753-9C28-39306169AFA1/bookmark.js:146:34)
    at Object.<anonymous> 

(/Users/xxx/Documents/backup/Alfred.alfredpreferences/workflows/user.workflow.06A3D3FF-F1D4-4753-9C28-39306169AFA1/index.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

**Comment by forclan** [comment]
想要看的数据似乎被你过滤掉了, 这个包里面开启了debug的log, 应该会有这样的日志: 

```
Mon, 17 Sep 2018 03:09:34 GMT getBookmarkInPinYin str {"url":"https://medium.com/graphql-mastery/json-as-an-argument-for-graphql-mutations-and-queries-3cd06d252a04","name":"Input object type as an argument for GraphQL mutations and queries"}
Mon, 17 Sep 2018 03:09:34 GMT getBookmarkInPinYin pin yin and raw data in getBookmarkInPinYin is Input object type as an argument for GraphQL mutations and queries Input object type as an argument 
```

主要就是埋点的信息: 

1. getBookmarkInPinYin allBookmarks
2. getBookmarkInPinYin str

前面那个表示获取到的所有书签,  后面对应的是对于单独一条数据的处理。
能看下'allBookmarks'这个数据是否为空, 然后贴一条数据吗。

**Comment by leoyeer** [comment]
Tue, 18 Sep 2018 03:10:19 GMT getBookmarkInPinYin str null
/Users/leoyeer/Documents/backup/Alfred.alfredpreferences/workflows/user.workflow.06A3D3FF-F1D4-4753-9C28-39306169AFA1/bookmark.js:149
        let pinyin = replaceHanZiWithPingYin(val.name);

**Comment by forclan** [comment]
allBookmarks也是空吗?
可以看一下`~/Library/Application Support/Google/Chrome/Default/Bookmarks`这个文件里面有内容吗。
现在怀疑是不是chrome安装位置的问题

**Comment by leoyeer** [comment]
有的。

**Comment by forclan** [comment]
`getBookmarkInPinYin allBookmarks`这条log的结果是像下面这样的一个数组吗。
或者能贴一下这个结果的数据吗, 只要有一条就行。
`getBookmarkInPinYin allBookmarks [ '{"url":"chrome://inspect/#service-workers","name":"Inspect"}']`

**Comment by leoyeer** [comment]
{
    "checksum": "951e75ed7e36716dd648a1c71122ed51",
    "roots": {
        "bookmark_bar": {
            "children": [
                {
                    "date_added": "13177419929753267",
                    "id": "421",
                    "meta_info": {
                        "last_visited_desktop": "13181302430859322"
                    },
                    "name": "xxx",
                    "sync_transaction_version": "1004",
                    "type": "url",
                    "url": "http://xxx"
                },
                {//内嵌文件夹
                    "children": [ {
                       "date_added": "13177419929753236",
                       "id": "407",
                       "name": "xxx",
                       "sync_transaction_version": "618",
                       "type": "url",
                       "url": "https://xxx"
                    }, {
                       "date_added": "13177419929753238",
                       "id": "408",
                       "name": "xxx",
                       "sync_transaction_version": "618",
                       "type": "url",
                       "url": "https://xxx"
                    } ],
                    "date_added": "13177419929802913",
                    "date_modified": "0",
                    "id": "406",
                    "name": "abc",
                    "sync_transaction_version": "618",
                    "type": "folder"
                 }
            ]
        }
    }
}

**Comment by leoyeer** [comment]
大致是这样一种结构，如果我肉眼没看错的话。 注意下文件夹可能还会内嵌文件夹

**Comment by leoyeer** [comment]
`{
    "checksum": "9",
    "roots": {
        "bookmark_bar": {
            "children": [
                {
                    "date_added": "13177419929753267",
                    "id": "421",
                    "meta_info": {
                        "last_visited_desktop": "13181302430859322"
                    },
                    "name": "xxx",
                    "sync_transaction_version": "1004",
                    "type": "url",
                    "url": "http://xxx"
                },
                {//内嵌文件夹
                    "children": [ {
                       "date_added": "13177419929753236",
                       "id": "407",
                       "name": "xxx",
                       "sync_transaction_version": "618",
                       "type": "url",
                       "url": "https://xxx"
                    }, {
                       "date_added": "13177419929753238",
                       "id": "408",
                       "name": "xxx",
                       "sync_transaction_version": "618",
                       "type": "url",
                       "url": "https://xxx"
                    } ],
                    "date_added": "13177419929802913",
                    "date_modified": "0",
                    "id": "406",
                    "name": "abc",
                    "sync_transaction_version": "618",
                    "type": "folder"
                 }
            ]
        }
    }
}`

**Comment by forclan** [comment]
下载一下这个: https://github.com/forclan/alfred-chrome-bookmark/blob/change/Chrome%20Bookmark%20for%20default%20user.alfredworkflow
现在怀疑你的书签里面有一些无效的书签, 导致在解析这些无效书签的时候出错错误了。

**Comment by leoyeer** [comment]
这个新的OK了。谢谢大佬

**Comment by leoyeer** [comment]
不过这个，好像用不了中文 ？

**Comment by forclan** [comment]
直接输拼音就行, 现在实现上是通过拼音来匹配的。

**Comment by leoyeer** [comment]
好的
